const express = require('express');
const bcrypt = require('bcryptjs');
const jwt = require('jsonwebtoken');
const db = require('../config/database');
const { authenticate, requireAdmin } = require('../middleware/authMiddleware');

const router = express.Router();
const SECRET = process.env.JWT_SECRET || 'cartify-development-secret';
const publicUser = u => ({ id:u.id,name:u.name,email:u.email,phone:u.phone,role:u.role,created_at:u.created_at });
const token = u => jwt.sign({id:u.id,email:u.email,role:u.role}, SECRET, {expiresIn:'7d'});
const slug = s => String(s).trim().toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');

// AUTH
router.post('/auth/signup', async (req,res,next)=>{ try { const {name,email,phone,password}=req.body; if(!name||!email||!password)return res.status(400).json({success:false,message:'Name, email and password are required'}); if(password.length<6)return res.status(400).json({success:false,message:'Password must be at least 6 characters'}); if(db.prepare('SELECT id FROM users WHERE email=?').get(email.trim().toLowerCase()))return res.status(409).json({success:false,message:'Email is already registered'}); const hash=await bcrypt.hash(password,12); const r=db.prepare('INSERT INTO users(name,email,phone,password_hash) VALUES(?,?,?,?)').run(name.trim(),email.trim().toLowerCase(),phone?.trim()||null,hash); const u=db.prepare('SELECT * FROM users WHERE id=?').get(r.lastInsertRowid); res.status(201).json({success:true,message:'Account created successfully',token:token(u),user:publicUser(u)}); }catch(e){next(e)} });
router.post('/auth/login', async (req,res,next)=>{ try { const {email,password}=req.body; const u=db.prepare('SELECT * FROM users WHERE email=?').get(String(email||'').trim().toLowerCase()); if(!u||!(await bcrypt.compare(password||'',u.password_hash)))return res.status(401).json({success:false,message:'Invalid email or password'}); res.json({success:true,message:'Login successful',token:token(u),user:publicUser(u)}); }catch(e){next(e)} });
router.get('/auth/me',authenticate,(req,res)=>{const u=db.prepare('SELECT id,name,email,phone,role,created_at FROM users WHERE id=?').get(req.user.id);res.json({success:true,user:u})});

// CATEGORIES
router.get('/categories',(req,res)=>res.json({success:true,categories:db.prepare('SELECT * FROM categories ORDER BY name').all()}));
router.post('/categories',authenticate,requireAdmin,(req,res,next)=>{try{const {name}=req.body;if(!name)return res.status(400).json({success:false,message:'Name is required'});const r=db.prepare('INSERT INTO categories(name,slug) VALUES(?,?)').run(name.trim(),slug(name));res.status(201).json({success:true,category:db.prepare('SELECT * FROM categories WHERE id=?').get(r.lastInsertRowid)})}catch(e){next(e)}});
router.put('/categories/:id',authenticate,requireAdmin,(req,res,next)=>{try{const {name}=req.body;if(!name)return res.status(400).json({success:false,message:'Name is required'});const r=db.prepare('UPDATE categories SET name=?,slug=? WHERE id=?').run(name.trim(),slug(name),req.params.id);if(!r.changes)return res.status(404).json({success:false,message:'Category not found'});res.json({success:true,category:db.prepare('SELECT * FROM categories WHERE id=?').get(req.params.id)})}catch(e){next(e)}});
router.delete('/categories/:id',authenticate,requireAdmin,(req,res)=>{const r=db.prepare('DELETE FROM categories WHERE id=?').run(req.params.id);if(!r.changes)return res.status(404).json({success:false,message:'Category not found'});res.json({success:true,message:'Category deleted'})});

// PRODUCTS
router.get('/products',(req,res,next)=>{try{let {search,category,brand,minPrice,maxPrice,sort='newest',page=1,limit=12}=req.query;page=Math.max(1,+page||1);limit=Math.min(100,Math.max(1,+limit||12));const c=[],p=[];if(search){c.push('(p.name LIKE ? OR p.description LIKE ? OR p.brand LIKE ?)');const q=`%${search}%`;p.push(q,q,q)}if(category){c.push('(c.slug=? OR c.id=?)');p.push(category,+category||0)}if(brand){c.push('p.brand=?');p.push(brand)}if(minPrice!==undefined){c.push('p.price>=?');p.push(+minPrice)}if(maxPrice!==undefined){c.push('p.price<=?');p.push(+maxPrice)}const orders={newest:'p.created_at DESC',price_asc:'p.price ASC',price_desc:'p.price DESC',rating:'p.rating DESC',name:'p.name ASC'};const where=c.length?'WHERE '+c.join(' AND '):'';const total=db.prepare(`SELECT COUNT(*) count FROM products p LEFT JOIN categories c ON c.id=p.category_id ${where}`).get(...p).count;const products=db.prepare(`SELECT p.*,c.name category_name,c.slug category_slug FROM products p LEFT JOIN categories c ON c.id=p.category_id ${where} ORDER BY ${orders[sort]||orders.newest} LIMIT ? OFFSET ?`).all(...p,limit,(page-1)*limit);res.json({success:true,products,pagination:{page,limit,total,pages:Math.ceil(total/limit)}})}catch(e){next(e)}});
router.get('/products/:id',(req,res)=>{const p=db.prepare('SELECT p.*,c.name category_name,c.slug category_slug FROM products p LEFT JOIN categories c ON c.id=p.category_id WHERE p.id=?').get(req.params.id);if(!p)return res.status(404).json({success:false,message:'Product not found'});const images=db.prepare('SELECT id,image_url FROM product_images WHERE product_id=?').all(req.params.id);res.json({success:true,product:{...p,images}})});
router.post('/products',authenticate,requireAdmin,(req,res,next)=>{try{const b=req.body;if(!b.name||b.price===undefined)return res.status(400).json({success:false,message:'Name and price are required'});const s=b.slug||slug(b.name);const r=db.prepare('INSERT INTO products(category_id,name,slug,description,brand,price,old_price,stock,rating,image) VALUES(?,?,?,?,?,?,?,?,?,?)').run(b.category_id||null,b.name.trim(),s,b.description||null,b.brand||null,+b.price,+b.old_price||null,+b.stock||0,+b.rating||0,b.image||null);res.status(201).json({success:true,product:db.prepare('SELECT * FROM products WHERE id=?').get(r.lastInsertRowid)})}catch(e){next(e)}});
router.put('/products/:id',authenticate,requireAdmin,(req,res,next)=>{try{const b=req.body;if(!db.prepare('SELECT id FROM products WHERE id=?').get(req.params.id))return res.status(404).json({success:false,message:'Product not found'});db.prepare('UPDATE products SET category_id=?,name=?,slug=?,description=?,brand=?,price=?,old_price=?,stock=?,rating=?,image=? WHERE id=?').run(b.category_id||null,b.name,b.slug||slug(b.name),b.description||null,b.brand||null,+b.price,+b.old_price||null,+b.stock||0,+b.rating||0,b.image||null,req.params.id);res.json({success:true,product:db.prepare('SELECT * FROM products WHERE id=?').get(req.params.id)})}catch(e){next(e)}});
router.delete('/products/:id',authenticate,requireAdmin,(req,res)=>{const r=db.prepare('DELETE FROM products WHERE id=?').run(req.params.id);if(!r.changes)return res.status(404).json({success:false,message:'Product not found'});res.json({success:true,message:'Product deleted'})});

function cart(userId){let c=db.prepare('SELECT * FROM carts WHERE user_id=?').get(userId);if(!c){const r=db.prepare('INSERT INTO carts(user_id) VALUES(?)').run(userId);c=db.prepare('SELECT * FROM carts WHERE id=?').get(r.lastInsertRowid)}return c}
function cartData(userId){const c=cart(userId);const items=db.prepare(`SELECT ci.id,ci.product_id,ci.quantity,p.name,p.price,p.image,p.stock,(ci.quantity*p.price) total FROM cart_items ci JOIN products p ON p.id=ci.product_id WHERE ci.cart_id=?`).all(c.id);return {cart_id:c.id,items,subtotal:items.reduce((s,i)=>s+i.total,0),count:items.reduce((s,i)=>s+i.quantity,0)}}
// CART
router.get('/cart',authenticate,(req,res)=>res.json({success:true,...cartData(req.user.id)}));
router.post('/cart',authenticate,(req,res,next)=>{try{const {product_id,quantity=1}=req.body,q=+quantity,p=db.prepare('SELECT * FROM products WHERE id=?').get(product_id);if(!p)return res.status(404).json({success:false,message:'Product not found'});if(q<1||q>p.stock)return res.status(400).json({success:false,message:'Invalid quantity or insufficient stock'});const c=cart(req.user.id),x=db.prepare('SELECT * FROM cart_items WHERE cart_id=? AND product_id=?').get(c.id,product_id);if(x){if(x.quantity+q>p.stock)return res.status(400).json({success:false,message:'Insufficient stock'});db.prepare('UPDATE cart_items SET quantity=quantity+? WHERE id=?').run(q,x.id)}else db.prepare('INSERT INTO cart_items(cart_id,product_id,quantity) VALUES(?,?,?)').run(c.id,product_id,q);db.prepare('UPDATE carts SET updated_at=CURRENT_TIMESTAMP WHERE id=?').run(c.id);res.status(201).json({success:true,...cartData(req.user.id)})}catch(e){next(e)}});
router.put('/cart/:itemId',authenticate,(req,res)=>{const q=+req.body.quantity,p=db.prepare('SELECT p.stock FROM cart_items ci JOIN products p ON p.id=ci.product_id JOIN carts c ON c.id=ci.cart_id WHERE ci.id=? AND c.user_id=?').get(req.params.itemId,req.user.id);if(!p)return res.status(404).json({success:false,message:'Cart item not found'});if(q<1||q>p.stock)return res.status(400).json({success:false,message:'Invalid quantity'});db.prepare('UPDATE cart_items SET quantity=? WHERE id=?').run(q,req.params.itemId);res.json({success:true,...cartData(req.user.id)})});
router.delete('/cart/:itemId',authenticate,(req,res)=>{db.prepare('DELETE FROM cart_items WHERE id IN (SELECT ci.id FROM cart_items ci JOIN carts c ON c.id=ci.cart_id WHERE ci.id=? AND c.user_id=?)').run(req.params.itemId,req.user.id);res.json({success:true,...cartData(req.user.id)})});
router.delete('/cart',authenticate,(req,res)=>{const c=cart(req.user.id);db.prepare('DELETE FROM cart_items WHERE cart_id=?').run(c.id);res.json({success:true,...cartData(req.user.id)})});

// WISHLIST
router.get('/wishlist',authenticate,(req,res)=>res.json({success:true,items:db.prepare('SELECT w.id,w.product_id,p.name,p.price,p.image,p.rating FROM wishlists w JOIN products p ON p.id=w.product_id WHERE w.user_id=? ORDER BY w.created_at DESC').all(req.user.id)}));
router.post('/wishlist/:productId',authenticate,(req,res)=>{if(!db.prepare('SELECT id FROM products WHERE id=?').get(req.params.productId))return res.status(404).json({success:false,message:'Product not found'});db.prepare('INSERT OR IGNORE INTO wishlists(user_id,product_id) VALUES(?,?)').run(req.user.id,req.params.productId);res.status(201).json({success:true,message:'Added to wishlist'})});
router.delete('/wishlist/:productId',authenticate,(req,res)=>{db.prepare('DELETE FROM wishlists WHERE user_id=? AND product_id=?').run(req.user.id,req.params.productId);res.json({success:true,message:'Removed from wishlist'})});

// ADDRESSES
router.get('/addresses',authenticate,(req,res)=>res.json({success:true,addresses:db.prepare('SELECT * FROM addresses WHERE user_id=? ORDER BY id DESC').all(req.user.id)}));
router.post('/addresses',authenticate,(req,res)=>{const b=req.body;if(!b.full_name||!b.phone||!b.address_line||!b.city||!b.governorate)return res.status(400).json({success:false,message:'Required address fields are missing'});const r=db.prepare('INSERT INTO addresses(user_id,full_name,phone,address_line,city,governorate,postal_code) VALUES(?,?,?,?,?,?,?)').run(req.user.id,b.full_name,b.phone,b.address_line,b.city,b.governorate,b.postal_code||null);res.status(201).json({success:true,address:db.prepare('SELECT * FROM addresses WHERE id=?').get(r.lastInsertRowid)})});
router.delete('/addresses/:id',authenticate,(req,res)=>{db.prepare('DELETE FROM addresses WHERE id=? AND user_id=?').run(req.params.id,req.user.id);res.json({success:true,message:'Address deleted'})});

// ORDERS
router.post('/orders',authenticate,(req,res,next)=>{try{const {address_id,payment_method='COD'}=req.body,c=cart(req.user.id),items=db.prepare('SELECT ci.product_id,ci.quantity,p.name,p.price,p.stock FROM cart_items ci JOIN products p ON p.id=ci.product_id WHERE ci.cart_id=?').all(c.id);if(!items.length)return res.status(400).json({success:false,message:'Cart is empty'});if(!['COD','MockCard'].includes(payment_method))return res.status(400).json({success:false,message:'Invalid payment method'});if(address_id&&!db.prepare('SELECT id FROM addresses WHERE id=? AND user_id=?').get(address_id,req.user.id))return res.status(400).json({success:false,message:'Invalid address'});for(const i of items)if(i.quantity>i.stock)return res.status(400).json({success:false,message:`Insufficient stock for ${i.name}`});const subtotal=items.reduce((s,i)=>s+i.quantity*i.price,0),shipping=subtotal>=1000?0:60,total=subtotal+shipping;const create=db.transaction(()=>{const o=db.prepare('INSERT INTO orders(user_id,address_id,payment_method,subtotal,shipping_fee,total) VALUES(?,?,?,?,?,?)').run(req.user.id,address_id||null,payment_method,subtotal,shipping,total);for(const i of items){db.prepare('INSERT INTO order_items(order_id,product_id,product_name,quantity,unit_price,total) VALUES(?,?,?,?,?,?)').run(o.lastInsertRowid,i.product_id,i.name,i.quantity,i.price,i.quantity*i.price);db.prepare('UPDATE products SET stock=stock-? WHERE id=?').run(i.quantity,i.product_id)}db.prepare('DELETE FROM cart_items WHERE cart_id=?').run(c.id);return o.lastInsertRowid});const id=create();res.status(201).json({success:true,message:'Order created successfully',order:getOrder(id,req.user.id)})}catch(e){next(e)}});
function getOrder(id,userId){const o=db.prepare(`SELECT o.*,a.full_name,a.phone,a.address_line,a.city,a.governorate,a.postal_code FROM orders o LEFT JOIN addresses a ON a.id=o.address_id WHERE o.id=? AND o.user_id=?`).get(id,userId);if(!o)return null;o.items=db.prepare('SELECT * FROM order_items WHERE order_id=?').all(id);return o}
router.get('/orders',authenticate,(req,res)=>res.json({success:true,orders:db.prepare('SELECT * FROM orders WHERE user_id=? ORDER BY created_at DESC').all(req.user.id)}));
router.get('/orders/:id',authenticate,(req,res)=>{const o=getOrder(req.params.id,req.user.id);if(!o)return res.status(404).json({success:false,message:'Order not found'});res.json({success:true,order:o})});
router.patch('/orders/:id/cancel',authenticate,(req,res,next)=>{try{const o=db.prepare('SELECT * FROM orders WHERE id=? AND user_id=?').get(req.params.id,req.user.id);if(!o)return res.status(404).json({success:false,message:'Order not found'});if(['Delivered','Cancelled'].includes(o.status))return res.status(400).json({success:false,message:'Order cannot be cancelled'});const items=db.prepare('SELECT * FROM order_items WHERE order_id=?').all(o.id);const tx=db.transaction(()=>{for(const i of items)if(i.product_id)db.prepare('UPDATE products SET stock=stock+? WHERE id=?').run(i.quantity,i.product_id);db.prepare("UPDATE orders SET status='Cancelled' WHERE id=?").run(o.id)});tx();res.json({success:true,order:getOrder(o.id,req.user.id)})}catch(e){next(e)}});

// REVIEWS
router.get('/products/:productId/reviews',(req,res)=>res.json({success:true,reviews:db.prepare('SELECT r.id,r.rating,r.comment,r.created_at,u.name FROM reviews r JOIN users u ON u.id=r.user_id WHERE r.product_id=? ORDER BY r.created_at DESC').all(req.params.productId)}));
router.post('/products/:productId/reviews',authenticate,(req,res,next)=>{try{const rating=+req.body.rating;if(!db.prepare('SELECT id FROM products WHERE id=?').get(req.params.productId))return res.status(404).json({success:false,message:'Product not found'});if(rating<1||rating>5)return res.status(400).json({success:false,message:'Rating must be between 1 and 5'});db.prepare('INSERT INTO reviews(user_id,product_id,rating,comment) VALUES(?,?,?,?) ON CONFLICT(user_id,product_id) DO UPDATE SET rating=excluded.rating,comment=excluded.comment').run(req.user.id,req.params.productId,rating,req.body.comment||null);const avg=db.prepare('SELECT AVG(rating) avg FROM reviews WHERE product_id=?').get(req.params.productId).avg||0;db.prepare('UPDATE products SET rating=? WHERE id=?').run(Number(avg.toFixed(1)),req.params.productId);res.json({success:true,message:'Review saved'})}catch(e){next(e)}});

// ADMIN
router.get('/admin/stats',authenticate,requireAdmin,(req,res)=>{const count=t=>db.prepare(`SELECT COUNT(*) count FROM ${t}`).get().count;const sales=db.prepare("SELECT COALESCE(SUM(total),0) total FROM orders WHERE status!='Cancelled'").get().total;res.json({success:true,stats:{users:count('users'),products:count('products'),orders:count('orders'),categories:count('categories'),sales}})});
router.get('/admin/orders',authenticate,requireAdmin,(req,res)=>res.json({success:true,orders:db.prepare(`SELECT o.*,u.name user_name,u.email user_email FROM orders o JOIN users u ON u.id=o.user_id ORDER BY o.created_at DESC`).all()}));
router.patch('/admin/orders/:id/status',authenticate,requireAdmin,(req,res,next)=>{try{const allowed=['Pending','Processing','Shipped','Delivered','Cancelled'];if(!allowed.includes(req.body.status))return res.status(400).json({success:false,message:'Invalid status'});const o=db.prepare('SELECT * FROM orders WHERE id=?').get(req.params.id);if(!o)return res.status(404).json({success:false,message:'Order not found'});if(o.status!=='Cancelled'&&req.body.status==='Cancelled'){const items=db.prepare('SELECT * FROM order_items WHERE order_id=?').all(o.id);for(const i of items)if(i.product_id)db.prepare('UPDATE products SET stock=stock+? WHERE id=?').run(i.quantity,i.product_id)}db.prepare('UPDATE orders SET status=? WHERE id=?').run(req.body.status,o.id);res.json({success:true,order:db.prepare('SELECT * FROM orders WHERE id=?').get(o.id)})}catch(e){next(e)}});
router.get('/admin/users',authenticate,requireAdmin,(req,res)=>res.json({success:true,users:db.prepare('SELECT id,name,email,phone,role,created_at FROM users ORDER BY created_at DESC').all()}));
router.patch('/admin/users/:id/role',authenticate,requireAdmin,(req,res)=>{if(!['customer','admin'].includes(req.body.role))return res.status(400).json({success:false,message:'Invalid role'});const r=db.prepare('UPDATE users SET role=? WHERE id=?').run(req.body.role,req.params.id);if(!r.changes)return res.status(404).json({success:false,message:'User not found'});res.json({success:true,user:db.prepare('SELECT id,name,email,phone,role,created_at FROM users WHERE id=?').get(req.params.id)})});

module.exports = router;
